Parameters:
  InstanceType:
    Type: String
    Default: "c5.large"
  Port:
    Type: Number
    Default: "10578"
  Protocal:
    Type: String
    Default: "udp"
    AllowedValues:
      - "udp"
      - "tcp"
  VolumeSize:
    Type: Number
    Default: "8"
      

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
      -
        Name: "SkyrimTogether"
        Image: "docker.io/tiltedphoques/st-game-server"
        MemoryReservation: "2048"
        PortMappings:
        -
          ContainerPort: !Ref Port
          HostPort: !Ref Port
          Protocol: !Ref Protocal

  ECSService:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref ECSCluster
      LaunchType: "EC2"
      SchedulingStrategy: "DAEMON"
      TaskDefinition: !Ref TaskDefinition
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Open port for the server to listen on
      SecurityGroupIngress:
      - IpProtocol: !Ref Protocal
        FromPort: !Ref Port
        ToPort: !Ref Port
        CidrIp: "0.0.0.0/0"
  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2008-10-17
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AmazonEC2ContainerServiceforEC2Role'
  InstanceProfile: 
    Type: "AWS::IAM::InstanceProfile"
    Properties: 
      Path: "/"
      Roles: 
        - 
          Ref: "Role"
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      BlockDeviceMappings:
      - DeviceName: "/dev/xvda"
        Ebs:
          VolumeType: "gp2"
          DeleteOnTermination: "true"
          VolumeSize: !Ref VolumeSize
      ImageId: "ami-a64d9ade"
      InstanceType: !Ref InstanceType
      UserData: 
        Fn::Base64:
          !Join
          - ''
          - - "#!/bin/bash\n"
            - 'echo "ECS_CLUSTER='
            - !Ref ECSCluster
            - '" >> /etc/ecs/ecs.config'
      SecurityGroups:
      - !Ref SecurityGroup
      IamInstanceProfile: !Ref InstanceProfile
Outputs:
  InstanceId:
    Value: !Ref Instance
  
